### ISSUE TITLE
Error during import.

### ISSUE THREAD

**Issue by sgongar** [Simulmedia/pyembedpg#1]
Hello!
I just downloaded this module using pip and when I try to import it I get an ImportError.
I'm using Python 2.7 on a clean Debian 8 installation.

Could somebody check if the setup.py file is alright?

Thanks.

**Comment by darthbear** [comment]
Thanks @sgongar for the bug report. It was a mistake on our end. It should be fixed now in `pyembedpg==0.0.3`. Thanks!

**Comment by sgongar** [comment]
You're welcome! ;)
