### ISSUE TITLE
Update this version to latest ones since its failing with 2.6 version of psycopg2

### ISSUE THREAD

**Issue by sunil-iquanti** [Simulmedia/pyembedpg#2]
https://github.com/Simulmedia/pyembedpg/blob/f0d09640109a77933381b933745f53aa0b6eca2e/setup.py#L65

Error seen with this installation is
`Error: could not determine PostgreSQL version from '10.3'`

**Comment by Cediddi** [comment]
This is frustrating, Also we now have psycopg2-wheel package too.

**Comment by mduwalsh** [comment]
Could you please also add support for python 3.5, 3.6 and 3.6?

**Comment by darthbear** [comment]
This should be fixed now in `pyembedpg==0.0.4`
